# ----------------------------------------
#   Configuration File for Report plugin
# ----------------------------------------
    
# Spam filter minimums
minimum:

    # Minimum levenshtein distance for determining string similarity
    distance: 6
    
    # Minimum word count for determining spam probability
    words: 3